[package]
name = "rusky-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mlua = { version = "0.6.5", features = ["luajit"] }
rusky-core = { path = "../rusky-core" }
